AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A starter AWS Lambda function.
Resources:
  HelloWorldpython37:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_hello_world.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: A starter AWS Lambda function.
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::000000000000:role/service-role/Hello-World-Python'
      Tags:
        'lambda-console:blueprint': hello-world-python
